const HOTEL = [
    {
        "id": "el1",
        "name": "Liana Beach Hotel & Spa",
        "img": "./img/hotels/1.jpg",
        "city": "Aranda de Duero",
        "rev":"641 reviews",
        "classHidden": "",
        "price": 13600,
    },
    {
        "id": "el2",
        "name": "Taki's Guests AFFINITY",
        "img": "./img/hotels/2.jpg",
        "city": "Peñaranda de Duero",
        "rev":"1,669 reviews",
        "classHidden": "",
        "price": 23900,
    },
    {
        "id": "el3",
        "name": "Hotel AspasiaFLAT",
        "img": "./img/hotels/3.jpg",
        "city": "El Burgo de Osma",
        "rev":"1,010 reviews",
        "classHidden": "",
        "price": 21600,
    },
    {
        "id": "el4",
        "name": "Nissaki Beach Hotel EBONY",
        "img": "./img/hotels/4.jpg",
        "city": "Serón de Nágima",
        "rev":"2,543 reviews",
        "classHidden": "",
        "price": 19900,
    },
    {
        "id": "el5",
        "name": "Naxos Evilion HSS AWT",
        "img": "./img/hotels/5.jpg",
        "city": "Santa María de Huerta",
        "rev":"1,598 reviews",
        "classHidden": "",
        "price": 14500,
    },
    {
        "id": "el6",
        "name": "FENDER Grapes Hotel",
        "img": "./img/hotels/6.jpg",
        "city": "Nuévalos",
        "rev":"2,312 reviews",
        "classHidden": "",
        "price": 14600,
    },
    {
        "id": "el7",
        "name": "La Casa di Dolly AWT",
        "img": "./img/hotels/7.jpg",
        "city": "Aguilar de Ebro",
        "rev":"1,675 reviews",
        "classHidden": "",
        "price": 13600,
    },
    {
        "id": "el8",
        "name": "Naxos Dream Oniro Studios",
        "img": "./img/hotels/8.jpg",
        "city": "Lalueza",
        "rev":"1,675 reviews",
        "classHidden": "",
        "price": 28700,
    },
    {
        "id": "el9",
        "name": "Iliada Suites Adults only",
        "img": "./img/hotels/9.jpg",
        "city": "Morata de Jiloca",
        "rev":"616 reviews",
        "classHidden": "",
        "price": 18100,
    },
    {
        "id": "el10",
        "name": "Aegeon Apartments WHITE",
        "img": "./img/hotels/10.jpg",
        "city": "El Burgo de Osma",
        "rev":"598 reviews",
        "classHidden": "card-link--hidden",
        "price": 18100,
    },
    {
        "id": "el11",
        "name": "Crystal Mare Suites",
        "img": "./img/hotels/11.jpg",
        "city": "Aguilar de Ebro",
        "rev":"1,191 reviews",
        "classHidden": "card-link--hidden",
        "price": 18100,
    },
    {
        "id": "el12",
        "name": "Liana Beach Hotel & Spa",
        "img": "./img/hotels/12.jpg",
        "city": "Mediana de Aragón",
        "rev":"1,669 reviews",
        "classHidden": "card-link--hidden",
        "price": 18100,
    },
    {
        "id": "el3",
        "name": "Jackson Euphoria Downtown",
        "img": "./img/hotels/13.jpg",
        "city": "Aguilar de Ebro",
        "rev":"1,975 reviews",
        "classHidden": "card-link--hidden",
        "price": 18100,
    },
    {
        "id": "el4",
        "name": "Kapetanos Rooms",
        "img": "./img/hotels/14.jpg",
        "city": "Santa Cruz de Grío",
        "rev":"3,611 reviews",
        "classHidden": "card-link--hidden",
        "price": 18100,
    },
    {
        "id": "el15",
        "name": "Archon Seaside Retreat",
        "img": "./img/hotels/15.jpg",
        "city": "Peñaranda de Duero",
        "rev":"1,344 reviews",
        "classHidden": "card-link--hidden",
        "price": 15990,
    }
]

const checkFilter = [
    {   "id": "1",
        "filt":"З аквапарком",
        "visibility": "hidden-non"
    },
    {   "id": "2",
        "filt":"Готельний комплекс",
        "visibility": "hidden-non"
    },
    {   "id": "3",
        "filt":"Клубний готель",
        "visibility": "hidden-non"
    },
    {   "id": "4",
        "filt":"Заміський готель",
        "visibility": "hidden-non"
    },
    {   "id": "5",
        "filt":"Оздоровчий комплекс",
        "visibility": "hidden-non"
    },
    {   "id": "6",
        "filt":"СПА-готель",
        "visibility": "checkbox--hidden"
    },
    {   "id": "7",
        "filt":"Приватний готель",
        "visibility": "checkbox--hidden"
    },
    {   "id": "8",
        "filt":"Парк-готель",
        "visibility": "checkbox--hidden"
    },
]